FROM python:3.9-buster

RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf \
    automake \
    build-essential \
    libtool

ENV PYTHONPATH=/

WORKDIR ${PYTHONPATH}

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt