IMG ?= iter8-analytics:latest

BASEIMG ?= iter8/iter8-analytics-base:latest

ITER8_ANALYTICS_METRICS_BACKEND_URL ?= http://localhost:9090
ITER8_ANALYTICS_DEBUG_ENV ?= false

# HELM
HELM_VERSION ?= v$(shell helm version --client --short | sed 's/.*v\([0-9]*\).*/\1/')
ifeq ($(HELM_VERSION),v2)
HELM2_NAME := --name iter8-analytics
HELM3_NAME := 
HELM_INCLUDE_OPTION := -x
else
HELM2_NAME := 
HELM3_NAME := iter8-analytics
HELM_INCLUDE_OPTION := -s
endif

all: build-default

clean-pyc:
	find iter8_analytics -type f \
	  \( -name '__pycache__' -o -name '*.pyc' -o -name '*.pyo' -o -name '*~' \) \
	-exec rm -f {} +

# Deploy analytics engine to the Kubernetes cluster configured in $KUBECONFIG or ~/.kube/config
deploy:
	helm template ${HELM3_NAME} install/kubernetes/helm/iter8-analytics ${HELM2_NAME} \
	  --set image.repository=`echo ${IMG} | cut -f1 -d':'` \
	  --set image.tag=`echo ${IMG} | cut -f2 -d':'` \
	| kubectl apply -f -

docker-run: docker-cleanup docker-build
	docker run -d --name iter8-analytics \
	  -p 5555:5555 \
	  -e ITER8_ANALYTICS_SERVER_PORT=5555 \
	  -e ITER8_ANALYTICS_METRICS_BACKEND_URL=${ITER8_ANALYTICS_METRICS_BACKEND_URL} \
	  -e ITER8_ANALYTICS_DEBUG_ENV=${ITER8_ANALYTICS_DEBUG_ENV} \
	${IMG}

docker-build: clean-pyc
	docker build . -t ${IMG}

docker-build-base: clean-pyc
	docker build . -f Dockerfile.base.img -t ${BASEIMG}

docker-push:
	docker push ${IMG}

docker-push-base:
	docker push ${BASEIMG}

docker-cleanup:
	docker rm -f iter8-analytics 2>/dev/null || true

build-default:
	echo '# Generated by make build-default; DO NOT EDIT' > install/kubernetes/iter8-analytics.yaml
	helm template ${HELM3_NAME} install/kubernetes/helm/iter8-analytics  ${HELM2_NAME} \
	>> install/kubernetes/iter8-analytics.yaml

.PHONY: changelog
changelog:
	@sed -n '/$(ver)/,/=====/p' CHANGELOG | grep -v $(ver) | grep -v "====="

test:
	coverage run --source=iter8_analytics --omit="*/__init__.py" -m pytest
	coverage html
