"""
Environment variables that control the iter8 analytics server
"""


UNMARSHAL_FILE_ENV = 'UNMARSHAL_FILE'

ITER8_ANALYTICS_LOG_LEVEL_ENV = 'ITER8_ANALYTICS_LOG_LEVEL'  # used by fastapi
LOG_LEVEL = 'logLevel'
LOG_LEVEL_DEFAULT_LEVEL = 'debug'

ANALYTICS_SERVICE_PORT = 'ANALYTICS_SERVICE_PORT'
ANALYTICS_SERVICE_DEFAULT_PORT = 8080
ANALYTICS_SERVICE_CONFIGFILE_PORT = 'port'
ANALYTICS_SERVICE_PORT_ENV = 'ITER8_ANALYTICS_SERVER_PORT'
